//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("center ver:1.4.30607.1")]
[assembly: AssemblyDescription("centers the current console window.")]
[assembly: AssemblyCompany("Bricksoft.com")]
[assembly: AssemblyProduct("center")]
[assembly: AssemblyCopyright("Copyright (C) 2010-2013 Kody Brown. Application and source code released under th" +
    "e MIT License.")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("594CA055-3BF8-47EC-B5C1-F8B57390396C")]
[assembly: AssemblyVersion("1.4.30607.1")]
[assembly: AssemblyFileVersion("1.4.30607.1")]


